#!/bin/sh
#
# ci_post_clone.sh — Xcode Cloud post-clone setup for this Flutter + native-TDLib app.
#
# Xcode Cloud checks out the repo clean and runs `xcodebuild` directly, but several
# build inputs are NOT in git (they're generated by Flutter or by a native build):
#   - ios/Flutter/ephemeral/...           (incl. FlutterGeneratedPluginSwiftPackage)
#   - ios/Flutter/Generated.xcconfig
#   - lib/config/secrets.dart             (Telegram api id / hash)
#   - ios/tdjson/tdjson.xcframework       (native TDLib — git-ignored build artifact)
#   - ios/Pods/
# This script recreates all of them so the Xcode Cloud archive can build.
#
# REQUIRED Xcode Cloud environment variables (Workflow → Environment → Environment
# Variables):
#   TELEGRAM_API_ID     integer
#   TELEGRAM_API_HASH   string   (mark as Secret)
# Optional:
#   TDJSON_XCFRAMEWORK_URL   override the prebuilt-framework download (see default below)
#
# The prebuilt tdjson.xcframework is hosted on a public GitHub release rather than
# rebuilt here, because building TDLib + OpenSSL for iOS takes ~40 min. To refresh
# it, rebuild locally (TDLib example/ios/build.sh, iOS only), re-zip, and upload to
# a new ios-tdjson-<ver> release, then bump the URL.

set -e

FLUTTER_VERSION="3.44.2"
TDJSON_URL="${TDJSON_XCFRAMEWORK_URL:-https://github.com/iebb/mithka/releases/download/ios-tdjson-1.8.65/tdjson-ios.xcframework.zip}"

# Xcode Cloud checks the repo out here; fall back to walking up from this script.
REPO="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/../.." && pwd)}"
cd "$REPO"
echo "▸ repo root: $REPO"

# --- Flutter SDK (pinned) ---------------------------------------------------
if ! command -v flutter >/dev/null 2>&1; then
  echo "▸ installing Flutter $FLUTTER_VERSION"
  git clone --depth 1 -b "$FLUTTER_VERSION" https://github.com/flutter/flutter.git "$HOME/flutter"
  export PATH="$HOME/flutter/bin:$PATH"
fi
flutter --version

# --- Telegram credentials → lib/config/secrets.dart ------------------------
: "${TELEGRAM_API_ID:?set TELEGRAM_API_ID in the Xcode Cloud workflow environment}"
: "${TELEGRAM_API_HASH:?set TELEGRAM_API_HASH in the Xcode Cloud workflow environment}"
echo "▸ writing lib/config/secrets.dart"
mkdir -p lib/config
cat > lib/config/secrets.dart <<EOF
class Secrets {
  static const int apiId = ${TELEGRAM_API_ID};
  static const String apiHash = '${TELEGRAM_API_HASH}';
  static bool get isConfigured => apiId != 0 && apiHash.isNotEmpty;
}
EOF

# --- Native TDLib framework (git-ignored; prebuilt on a public release) ------
if [ ! -d "ios/tdjson/tdjson.xcframework" ]; then
  echo "▸ downloading tdjson.xcframework"
  mkdir -p ios/tdjson
  curl -fL "$TDJSON_URL" -o /tmp/tdjson.zip
  unzip -q -o /tmp/tdjson.zip -d ios/tdjson
fi
ls -d ios/tdjson/tdjson.xcframework

# --- Flutter iOS build inputs (Generated.xcconfig, plugin pods) --------------
# Keep Swift Package Manager OFF: the project is CocoaPods-only on purpose (SPM
# produced App Store IPAs missing the SwiftSupport folder → ITMS-90426). A fresh
# runner defaults SPM on, so disable it before generating the project.
echo "▸ generating Flutter iOS build inputs"
flutter config --no-enable-swift-package-manager
flutter precache --ios
flutter pub get
flutter build ios --config-only --release

# --- CocoaPods --------------------------------------------------------------
if ! command -v pod >/dev/null 2>&1; then
  echo "▸ installing CocoaPods"
  brew install cocoapods || sudo gem install cocoapods
fi
echo "▸ pod install"
cd ios && pod install

echo "✓ ci_post_clone complete"
