#!/bin/sh
#
# ci_post_clone.sh — Xcode Cloud post-clone setup for this Flutter + native-TDLib app.
#
# Xcode Cloud checks out the repo clean and runs `xcodebuild` directly, but several
# build inputs are NOT in git (they're generated by Flutter or by a native build):
#   - ios/Flutter/ephemeral/...           (incl. FlutterGeneratedPluginSwiftPackage)
#   - ios/Flutter/Generated.xcconfig
#   - lib/config/secrets.dart             (Telegram api id / hash)
#   - ios/tdjson/tdjson.xcframework       (native TDLib — git-ignored build artifact)
#   - ios/Pods/
# This script recreates all of them so the Xcode Cloud archive can build.
#
# REQUIRED Xcode Cloud environment variables (Workflow → Environment → Environment
# Variables):
#   TELEGRAM_API_ID     integer
#   TELEGRAM_API_HASH   string   (mark as Secret)
#   FIREBASE_IOS_GOOGLESERVICE_INFO_PLIST_B64
#                      base64 of ios/Runner/GoogleService-Info.plist
# Optional:
#   TDJSON_XCFRAMEWORK_URL   override the prebuilt-framework download (see default below)
#
# The prebuilt tdjson.xcframework is hosted in the sibling mithka-tdjson repo
# rather than rebuilt here, because building TDLib + OpenSSL for iOS takes
# ~40 min. To refresh it, rebuild locally, re-zip, upload a new release asset to
# iebb/mithka-tdjson, then bump the URL.

set -e

FLUTTER_VERSION="3.44.2"
TDJSON_URL="${TDJSON_XCFRAMEWORK_URL:-https://github.com/iebb/mithka-tdjson/releases/download/tdjson-1.8.65-ios13/tdjson-ios.xcframework.zip}"

# Xcode Cloud checks the repo out here; fall back to walking up from this script.
REPO="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/../.." && pwd)}"
cd "$REPO"
echo "▸ repo root: $REPO"
GIT_COMMIT="$(git rev-parse --short HEAD)"
echo "▸ git commit: $GIT_COMMIT"

# Xcode Cloud runs xcodebuild after this script and can otherwise keep using
# stale FLUTTER_BUILD_NAME values from the checked-in project. Keep the archive
# version sourced from pubspec.yaml, matching the Android/GitHub release flow.
RAW_VERSION="$(awk '/^version:/ { print $2; exit }' pubspec.yaml)"
test -n "$RAW_VERSION"
APP_BUILD_NAME="${RAW_VERSION%%+*}"
APP_BUILD_NUMBER="${RAW_VERSION#*+}"
if [ "$APP_BUILD_NUMBER" = "$RAW_VERSION" ]; then
  APP_BUILD_NUMBER=1
fi
IFS=. read -r APP_VERSION_MAJOR APP_VERSION_MINOR APP_VERSION_PATCH <<EOF
$APP_BUILD_NAME
EOF
APP_VERSION_PATCH=$((APP_VERSION_PATCH - APP_VERSION_PATCH % 4))
XCODE_BUILD_NAME="${APP_VERSION_MAJOR}.${APP_VERSION_MINOR}.${APP_VERSION_PATCH}"
echo "▸ app version: $APP_BUILD_NAME+$APP_BUILD_NUMBER"
echo "▸ Xcode Cloud App Store version override: $XCODE_BUILD_NAME+$APP_BUILD_NUMBER"
python3 - <<PY
from pathlib import Path
path = Path("ios/Runner.xcodeproj/project.pbxproj")
text = path.read_text()
text = __import__("re").sub(r"FLUTTER_BUILD_NAME = [^;]+;", "FLUTTER_BUILD_NAME = ${XCODE_BUILD_NAME};", text)
text = __import__("re").sub(r"MARKETING_VERSION = [^;]+;", "MARKETING_VERSION = ${XCODE_BUILD_NAME};", text)
text = __import__("re").sub(r"CURRENT_PROJECT_VERSION = (?!\"\\$\\(FLUTTER_BUILD_NUMBER\\)\")[^;]+;", "CURRENT_PROJECT_VERSION = ${APP_BUILD_NUMBER};", text)
path.write_text(text)
PY

# --- Flutter SDK (pinned) ---------------------------------------------------
if ! command -v flutter >/dev/null 2>&1; then
  echo "▸ installing Flutter $FLUTTER_VERSION"
  git clone --depth 1 -b "$FLUTTER_VERSION" https://github.com/flutter/flutter.git "$HOME/flutter"
  export PATH="$HOME/flutter/bin:$PATH"
fi
flutter --version

# --- Telegram credentials → lib/config/secrets.dart ------------------------
: "${TELEGRAM_API_ID:?set TELEGRAM_API_ID in the Xcode Cloud workflow environment}"
: "${TELEGRAM_API_HASH:?set TELEGRAM_API_HASH in the Xcode Cloud workflow environment}"
echo "▸ writing lib/config/secrets.dart"
mkdir -p lib/config
cat > lib/config/secrets.dart <<EOF
class Secrets {
  static const int apiId = ${TELEGRAM_API_ID};
  static const String apiHash = '${TELEGRAM_API_HASH}';
  static bool get isConfigured => apiId != 0 && apiHash.isNotEmpty;
}
EOF

# --- Firebase config → ios/Runner/GoogleService-Info.plist ------------------
: "${FIREBASE_IOS_GOOGLESERVICE_INFO_PLIST_B64:?set FIREBASE_IOS_GOOGLESERVICE_INFO_PLIST_B64 in the Xcode Cloud workflow environment}"
echo "▸ writing ios/Runner/GoogleService-Info.plist"
mkdir -p ios/Runner
printf '%s' "$FIREBASE_IOS_GOOGLESERVICE_INFO_PLIST_B64" | base64 -d > ios/Runner/GoogleService-Info.plist

# --- Native TDLib framework (git-ignored; prebuilt on a public release) ------
if [ ! -d "ios/tdjson/tdjson.xcframework" ]; then
  echo "▸ downloading tdjson.xcframework"
  mkdir -p ios/tdjson
  curl -fL "$TDJSON_URL" -o /tmp/tdjson.zip
  unzip -q -o /tmp/tdjson.zip -d ios/tdjson
fi
ls -d ios/tdjson/tdjson.xcframework
"$REPO/scripts/wrap-tdjson-xcframework.sh" ios/tdjson/tdjson.xcframework

# --- Flutter iOS build inputs (Generated.xcconfig, plugin pods) --------------
# Keep Swift Package Manager OFF: the project is CocoaPods-only on purpose (SPM
# produced App Store IPAs missing the SwiftSupport folder → ITMS-90426). A fresh
# runner defaults SPM on, so disable it before generating the project.
echo "▸ generating Flutter iOS build inputs"
flutter config --no-enable-swift-package-manager
flutter precache --ios
flutter pub get
flutter build ios --config-only --release \
  --build-name="$XCODE_BUILD_NAME" \
  --build-number="$APP_BUILD_NUMBER" \
  --dart-define="GIT_COMMIT=$GIT_COMMIT"

# --- CocoaPods --------------------------------------------------------------
if ! command -v pod >/dev/null 2>&1; then
  echo "▸ installing CocoaPods"
  brew install cocoapods || sudo gem install cocoapods
fi
echo "▸ pod install"
cd ios
# Xcode Cloud can restore or leave behind a stale Pods sandbox. The archive
# phase compares Podfile.lock with Pods/Manifest.lock, so rebuild the sandbox
# from the checked-in lockfile before xcodebuild runs.
rm -rf Pods
pod install --deployment
cp Podfile.lock Pods/Manifest.lock
diff -q Podfile.lock Pods/Manifest.lock
ls -l Podfile.lock Pods/Manifest.lock

echo "✓ ci_post_clone complete"
