#!/bin/sh
#
# ci_post_clone.sh — Xcode Cloud post-clone setup for this Flutter + native-TDLib app.
#
# Xcode Cloud checks out the repo clean and runs `xcodebuild` directly, but several
# build inputs are NOT in git (they're generated by Flutter or by a native build):
#   - ios/Flutter/ephemeral/...           (incl. FlutterGeneratedPluginSwiftPackage)
#   - ios/Flutter/Generated.xcconfig
#   - lib/config/secrets.dart             (Telegram api id / hash)
#   - ios/tdjson/tdjson.xcframework       (native TDLib — git-ignored build artifact)
#   - ios/Pods/
# This script recreates all of them so the Xcode Cloud archive can build.
#
# REQUIRED Xcode Cloud environment variables (Workflow → Environment → Environment
# Variables):
#   TELEGRAM_API_ID     integer
#   TELEGRAM_API_HASH   string   (mark as Secret)
#   FIREBASE_IOS_GOOGLESERVICE_INFO_PLIST_B64
#                      base64 of ios/Runner/GoogleService-Info.plist
# Optional:
#   TDJSON_XCFRAMEWORK_URL   override the prebuilt-framework download (see default below)
#   TGVOIP_WEBRTC_XCFRAMEWORK_URL
#                      override the pinned official Telegram iOS group-call XCFramework
#   TGVOIP_WEBRTC_XCFRAMEWORK_SHA256
#                      SHA-256 for the TgVoip override
#   REVIEW_RELAY             https://relay.example|sha256(normalized-phone-digits)
#   SENTRY_AUTH_TOKEN        upload iOS dSYMs to Sentry when set
#   SENTRY_ORG               Sentry org slug for dSYM upload; defaults to nekoko
#   SENTRY_PROJECT           Sentry project slug/id for dSYM upload; defaults to 10
#   SENTRY_URL               Sentry base URL; defaults to https://sentry.nekoko.it
#
# The prebuilt tdjson.xcframework is hosted in the sibling mithka-tdjson repo
# rather than rebuilt here, because building TDLib + OpenSSL for iOS takes
# ~40 min. The default URL is pinned so Xcode Cloud cannot pick a stale latest
# artifact without the Mithka session string backup symbols.

set -e

FLUTTER_VERSION="3.44.2"
TDJSON_RELEASE_TAG="tdlib-1.8.66-1b08c83bc078"
TDJSON_URL="${TDJSON_XCFRAMEWORK_URL:-https://github.com/iebb/mithka-tdjson/releases/download/${TDJSON_RELEASE_TAG}/tdjson-ios.xcframework.zip}"
TGVOIP_RELEASE_TAG="tgvoip-telegram-ios-6e370e06d147"
TGVOIP_URL="${TGVOIP_WEBRTC_XCFRAMEWORK_URL:-https://github.com/iebb/mithka-tdjson/releases/download/${TGVOIP_RELEASE_TAG}/tgvoip-ios.xcframework.zip}"
TGVOIP_SHA256="${TGVOIP_WEBRTC_XCFRAMEWORK_SHA256:-a1da44189af3802fcc0900696c5cdc549ffc2e53c5a2a0bab713a208aefe2737}"
CURL_RETRY_FLAGS="-fL --retry 5 --retry-delay 2 --connect-timeout 20"
if curl --help all 2>/dev/null | grep -q -- '--retry-all-errors'; then
  CURL_RETRY_FLAGS="$CURL_RETRY_FLAGS --retry-all-errors"
fi

retry() {
  attempts="$1"
  delay="$2"
  shift 2
  n=1
  while :; do
    "$@" && return 0
    status=$?
    if [ "$n" -ge "$attempts" ]; then
      echo "error: command failed after $attempts attempts: $*" >&2
      return "$status"
    fi
    echo "warning: command failed with exit $status; retry $((n + 1))/$attempts in ${delay}s: $*" >&2
    sleep "$delay"
    n=$((n + 1))
    delay=$((delay * 2))
  done
}

pod_install_with_retry() {
  attempts=4
  delay=8
  n=1
  while :; do
    rm -rf Pods
    pod_install_args="--deployment"
    if [ -d LocalPods/tgvoip/TgVoipWebrtc.xcframework ]; then
      # The optional local binary pod is added after checkout, so it cannot be
      # represented in the lockfile used by source-only contributor builds.
      pod_install_args=""
    fi
    # shellcheck disable=SC2086 # optional CocoaPods argument is intentionally split.
    if pod install $pod_install_args; then
      return 0
    fi
    status=$?
    if [ "$n" -ge "$attempts" ]; then
      echo "error: pod install failed after $attempts attempts" >&2
      return "$status"
    fi
    echo "warning: pod install failed with exit $status; clearing transient CocoaPods state and retrying $((n + 1))/$attempts in ${delay}s" >&2
    cleanup_cocoapods_transients
    sleep "$delay"
    n=$((n + 1))
    delay=$((delay * 2))
  done
}

cleanup_cocoapods_transients() {
  find "${TMPDIR:-/tmp}" -maxdepth 1 \( -name 'CocoaPods-*' -o -name 'd20*' \) -exec rm -rf {} + 2>/dev/null || true
  pod cache clean --all >/dev/null 2>&1 || true
}

flutter_build_ios_config_with_retry() {
  attempts=4
  delay=8
  n=1
  while :; do
    if flutter build ios --config-only --release \
      --build-name="$XCODE_BUILD_NAME" \
      --build-number="$APP_BUILD_NUMBER" \
      --dart-define="GIT_COMMIT=$GIT_COMMIT" \
      --dart-define="SENTRY_DSN=${SENTRY_DSN:-}" \
      --dart-define="SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-production}" \
      --dart-define="REVIEW_RELAY=${REVIEW_RELAY:-}"; then
      return 0
    fi
    status=$?
    if [ "$n" -ge "$attempts" ]; then
      echo "error: flutter build ios --config-only failed after $attempts attempts" >&2
      return "$status"
    fi
    echo "warning: flutter build ios --config-only failed with exit $status; clearing transient CocoaPods state and retrying $((n + 1))/$attempts in ${delay}s" >&2
    cleanup_cocoapods_transients
    sleep "$delay"
    n=$((n + 1))
    delay=$((delay * 2))
  done
}

decode_base64_to_file() {
  data="$1"
  output="$2"
  tmp="${output}.tmp"
  if printf '%s' "$data" | base64 --decode > "$tmp" 2>/dev/null ||
    printf '%s' "$data" | base64 -D > "$tmp" 2>/dev/null ||
    printf '%s' "$data" | base64 -d > "$tmp"; then
    mv "$tmp" "$output"
    return 0
  fi
  rm -f "$tmp"
  return 1
}

# Xcode Cloud checks the repo out here; fall back to walking up from this script.
REPO="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/../.." && pwd)}"
cd "$REPO"
echo "▸ repo root: $REPO"
GIT_COMMIT="$(git rev-parse --short HEAD)"
echo "▸ git commit: $GIT_COMMIT"

# Xcode Cloud runs xcodebuild after this script and can otherwise keep using
# stale Flutter values from the checked-in project. Keep the major/minor version
# from pubspec.yaml but force the iOS patch component to zero. Android nightlies
# can therefore advance independently (for example 0.8.2 becomes 0.8.0 on iOS).
RAW_VERSION="$(awk '/^version:/ { print $2; exit }' pubspec.yaml)"
test -n "$RAW_VERSION"
APP_BUILD_NAME="${RAW_VERSION%%+*}"
APP_BUILD_NUMBER="${RAW_VERSION#*+}"
if [ "$APP_BUILD_NUMBER" = "$RAW_VERSION" ] || [ -z "$APP_BUILD_NUMBER" ]; then
  APP_BUILD_NUMBER=1
fi
XCODE_BUILD_NAME="$(
  printf '%s\n' "$APP_BUILD_NAME" |
    awk -F. 'NF == 3 && $1 ~ /^[0-9]+$/ && $2 ~ /^[0-9]+$/ && $3 ~ /^[0-9]+$/ { print $1 "." $2 ".0" }'
)"
if [ -z "$XCODE_BUILD_NAME" ]; then
  echo "error: expected a numeric X.Y.Z version in pubspec.yaml, got $APP_BUILD_NAME" >&2
  exit 1
fi
echo "▸ iOS app version: $XCODE_BUILD_NAME+$APP_BUILD_NUMBER (source: $APP_BUILD_NAME)"
python3 - <<PY
from pathlib import Path
path = Path("ios/Runner.xcodeproj/project.pbxproj")
text = path.read_text()
text = __import__("re").sub(r"FLUTTER_BUILD_NAME = [^;]+;", "FLUTTER_BUILD_NAME = ${XCODE_BUILD_NAME};", text)
text = __import__("re").sub(r"MARKETING_VERSION = [^;]+;", "MARKETING_VERSION = ${XCODE_BUILD_NAME};", text)
text = __import__("re").sub(r"CURRENT_PROJECT_VERSION = (?!\"\\$\\(FLUTTER_BUILD_NUMBER\\)\")[^;]+;", "CURRENT_PROJECT_VERSION = ${APP_BUILD_NUMBER};", text)
path.write_text(text)
PY

# --- Flutter SDK (pinned) ---------------------------------------------------
if ! command -v flutter >/dev/null 2>&1; then
  echo "▸ installing Flutter $FLUTTER_VERSION"
  retry 3 10 git clone --depth 1 -b "$FLUTTER_VERSION" https://github.com/flutter/flutter.git "$HOME/flutter"
  export PATH="$HOME/flutter/bin:$PATH"
fi
flutter --version

# --- Telegram credentials → lib/config/secrets.dart ------------------------
: "${TELEGRAM_API_ID:?set TELEGRAM_API_ID in the Xcode Cloud workflow environment}"
: "${TELEGRAM_API_HASH:?set TELEGRAM_API_HASH in the Xcode Cloud workflow environment}"
echo "▸ writing lib/config/secrets.dart"
mkdir -p lib/config
cat > lib/config/secrets.dart <<EOF
class Secrets {
  static const int apiId = ${TELEGRAM_API_ID};
  static const String apiHash = '${TELEGRAM_API_HASH}';
  static bool get isConfigured => apiId != 0 && apiHash.isNotEmpty;
}
EOF

# --- Firebase config → ios/Runner/GoogleService-Info.plist ------------------
mkdir -p ios/Runner
if [ -n "${FIREBASE_IOS_GOOGLESERVICE_INFO_PLIST_B64:-}" ]; then
  echo "▸ writing ios/Runner/GoogleService-Info.plist"
  decode_base64_to_file "$FIREBASE_IOS_GOOGLESERVICE_INFO_PLIST_B64" ios/Runner/GoogleService-Info.plist
elif [ -f ios/Runner/GoogleService-Info.plist ]; then
  echo "▸ using existing ios/Runner/GoogleService-Info.plist"
else
  echo "error: set FIREBASE_IOS_GOOGLESERVICE_INFO_PLIST_B64 in the Xcode Cloud workflow environment" >&2
  exit 1
fi

# --- Native TDLib framework (git-ignored; prebuilt on a public release) ------
echo "▸ downloading tdjson.xcframework"
mkdir -p ios/tdjson
rm -rf ios/tdjson/tdjson.xcframework /tmp/tdjson.zip
# shellcheck disable=SC2086 # CURL_RETRY_FLAGS is intentionally split.
retry 4 5 curl $CURL_RETRY_FLAGS "$TDJSON_URL" -o /tmp/tdjson.zip
unzip -q -o /tmp/tdjson.zip -d ios/tdjson
ls -d ios/tdjson/tdjson.xcframework
"$REPO/scripts/wrap-tdjson-xcframework.sh" ios/tdjson/tdjson.xcframework
"$REPO/scripts/check-tdjson-session-symbols.sh" ios/tdjson/tdjson.xcframework

echo "▸ downloading TgVoipWebrtc.xcframework"
rm -rf ios/LocalPods/tgvoip/TgVoipWebrtc.xcframework /tmp/tgvoip.zip
# shellcheck disable=SC2086 # CURL_RETRY_FLAGS is intentionally split.
retry 4 5 curl $CURL_RETRY_FLAGS "$TGVOIP_URL" -o /tmp/tgvoip.zip
printf '%s  %s\n' "$TGVOIP_SHA256" /tmp/tgvoip.zip | shasum -a 256 -c -
unzip -q -o /tmp/tgvoip.zip -d ios/LocalPods/tgvoip
ls -d ios/LocalPods/tgvoip/TgVoipWebrtc.xcframework

# --- Flutter iOS build inputs (Generated.xcconfig, plugin pods) --------------
# Keep Swift Package Manager OFF: the project is CocoaPods-only on purpose (SPM
# produced App Store IPAs missing the SwiftSupport folder → ITMS-90426). A fresh
# runner defaults SPM on, so disable it before generating the project.
echo "▸ generating Flutter iOS build inputs"
flutter config --no-enable-swift-package-manager
flutter precache --ios
flutter pub get
flutter_build_ios_config_with_retry
python3 - <<PY >> ios/Flutter/Generated.xcconfig
import os
import urllib.parse

dsn = os.environ.get("SENTRY_DSN", "")
environment = os.environ.get("SENTRY_ENVIRONMENT", "production")
print("SENTRY_DSN_ENCODED=" + urllib.parse.quote(dsn, safe=""))
print("SENTRY_ENVIRONMENT=" + environment.replace("\\n", "").replace("\\r", ""))
PY

# --- CocoaPods --------------------------------------------------------------
if ! command -v pod >/dev/null 2>&1; then
  echo "▸ installing CocoaPods"
  retry 3 10 brew install cocoapods || retry 3 10 sudo gem install cocoapods
fi
echo "▸ pod install"
cd ios
# Xcode Cloud can restore or leave behind a stale Pods sandbox. The archive
# phase compares Podfile.lock with Pods/Manifest.lock, so rebuild the sandbox
# from the checked-in lockfile before xcodebuild runs.
pod_install_with_retry
cp Podfile.lock Pods/Manifest.lock
diff -q Podfile.lock Pods/Manifest.lock
ls -l Podfile.lock Pods/Manifest.lock

echo "✓ ci_post_clone complete"
